# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FCMTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FCMTest
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'FCMTestTests' do
    inherit! :search_paths
  end

  target 'FCMTestUITests' do
    # Pods for testing
  end
  
  target 'Notification Service Extension' do
    # Pods for testing
    pod 'Firebase/Messaging'
  end

end
